name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:humble-desktop
    strategy:
      matrix:
        os: [ubuntu-lastest]
      fail-fast: false
    steps:
      - name: Source ROS2
        run: source /opt/ros/humble/setup.sh
      - name: Make workspace
        run: mkdir -p __w/src && vcs import src/ --input https://raw.githubusercontent.com/santiago-tapia/sandbox/main/my.repos
      - name: Install deps
        run: rosdep install -i --from-path src --rosdistro humble -y
      - name: Build
        run: colcon build --symlink-install --event-handlers=console_cohesion+
