name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:humble-desktop
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3
        with:
          package-name: prototype
          target-ros2-distro: humble
          vcs-repo-file-url: https://raw.githubusercontent.com/santiago-tapia/sandbox/main/my.repos
