name: main

on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:humble-desktop
    strategy:
      matrix:
        os: [ubuntu-lastest]
      fail-fast: false
    steps:
      - name: Source ROS2
      # Atention: commands run on shell not on bash
        run: . /opt/ros/humble/setup.sh && echo "source humble done"
      - name: Make workspace
        run: mkdir -p __w/src && cd __w && vcs import src/ --input https://raw.githubusercontent.com/santiago-tapia/sandbox/main/my.repos
      - name: Install deps
        run: cd __w && rosdep install -i --from-path src --rosdistro humble -y
      - name: Build
        run: . /opt/ros/humble/setup.sh && colcon build --symlink-install --event-handlers=console_cohesion+
